services:
  selcoool_nextjs:
    container_name: selcoool_nextjs
    restart: always
    build:
      context: ./
    # ports:
    #   - "3000:3000"
    networks:
      - root_rent_room_network
    env_file:
      - .env.local

networks:
  root_rent_room_network:
    external: true