name: Deploy to VPS NEST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH to VPS and update project
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}  # Use password if you are using SSH password
        # key: ${{ secrets.VPS_SSH_KEY }}  # Use SSH key if applicable
        script: |
          # Check if the project directory exists
          if [ -d "/root/selcoool_nextjs" ]; then
            echo "Directory exists. Removing it..."
            rm -rf /root/selcoool_nextjs
            mkdir -p /root/selcoool_nextjs
            cd /root/selcoool_nextjs
            git clone https://github.com/${{ github.repository }} /root/selcoool_nextjs
            if [ -f ".next.zip" ]; then
            unzip .next.zip -d ./
            fi
            # Build and start the Docker containers
            docker-compose -f docker-compose-selcoool_nextjs.yml up -d --build
            docker system prune -f
            # Restart Nginx
            cd ~
            docker-compose -f docker-compose-nginx.yml restart nginx

          else
            echo "Directory does not exist. Proceeding..."
            mkdir -p /root/selcoool_nextjs
            cd /root/selcoool_nextjs
            git clone https://github.com/${{ github.repository }} /root/selcoool_nextjs
            if [ -f ".next.zip" ]; then
            unzip .next.zip -d ./
            fi
            # Build and start the Docker containers
            docker-compose -f docker-compose-selcoool_nextjs.yml up -d --build
            docker system prune -f
            # Restart Nginx
            cd ~
            docker-compose -f docker-compose-nginx.yml restart nginx
          fi















          # # Create the project directory and clone the repository
          # mkdir -p /root/selcoool_010924
          # cd /root/selcoool_010924
          # git clone https://github.com/${{ github.repository }} .

          # # Unzip the .next.zip if present
          # if [ -f ".next.zip" ]; then
          #   unzip .next.zip -d ./
          # fi

          # # Build and start the Docker containers
          # docker-compose -f docker-compose-selcoool_010924.yml up -d --build
          
          # # Restart Nginx
          # cd ~
          # docker-compose -f docker-compose-nginx.yml restart nginx

          # echo "Deployment completed successfully."

        # script: |
        #   echo "Xoa thu muc du an"
        #   rm -rf /root/backend_040824
        #   echo "Xoa images and container"
          
        #   docker stop $(docker ps -aq) || true
        #   docker rm $(docker ps -aq) || true
        #   docker rmi $(docker images -q) || true
        #   docker-compose -f docker-compose-api-backend_040824.yml down
        #   docker system prune -a -f
        #   sudo systemctl restart docker
        #   echo "Xoa du an 1"
