name: Deploy to VPS NEST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH to VPS and update project
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}  # Use password if you are using SSH password
        # key: ${{ secrets.VPS_SSH_KEY }}  # Use SSH key if applicable
        script: |
          script: |
          # Xóa thư mục nếu đã tồn tại và tạo mới
          if [ -d "/root/selcoool_nextjs" ]; then
            echo "Thư mục /root/selcoool_nextjs đã tồn tại. Đang xóa..."
            rm -rf /root/selcoool_nextjs
          fi
          mkdir -p /root/selcoool_nextjs
          cd /root/selcoool_nextjs
          
          # Clone lại mã nguồn mới nhất từ GitHub
          git clone https://github.com/${{ github.repository }} . || git pull origin main

          # Build và khởi động Docker containers
          docker-compose -f docker-compose-selcoool_nextjs.yml up -d --build || { echo "Docker Compose failed!"; exit 1; }
          
          # Dọn dẹp các Docker images không sử dụng
          docker system prune -f

          # Khởi động lại dịch vụ Nginx
          cd ~
          docker-compose -f docker-compose-nginx.yml restart nginx